#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
  path: /home 
  controller: App\Controller\HomeController::home
ticket.add:
    path: /ticket/add
    controller: App\Controller\TicketController::add
ticket.all:
    path: /ticket/all 
    controller: App\Controller\TicketController::all
app_ticket:
  path: /ticket
  controller: App\Controller\TicketController::homeTicket